import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Search } from "lucide-react";
import type { RequisitionRecord } from "@/lib/requisition/types";
import type { BoqRecord } from "@/lib/boq/types";

const fmtDate = (s: string | null | undefined) =>
  s ? new Date(s).toLocaleDateString("en-IN") : "—";

export default function RequisitionsList() {
  const [reqs, setReqs] = useState<RequisitionRecord[]>([]);
  const [boqs, setBoqs] = useState<Record<string, BoqRecord>>({});
  const [latestRevByRoot, setLatestRevByRoot] = useState<Record<string, number>>({});
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  useEffect(() => {
    (async () => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const sb = supabase as any;
      const { data: r } = await sb.from("requisitions").select("*").order("created_at", { ascending: false });
      const list = (r as RequisitionRecord[]) || [];
      setReqs(list);

      const boqIds = Array.from(new Set(list.map((x) => x.boq_id)));
      const rootIds = Array.from(new Set(list.map((x) => x.order_root_id)));
      if (boqIds.length) {
        const { data: b } = await supabase.from("boqs").select("*").in("id", boqIds);
        const map: Record<string, BoqRecord> = {};
        ((b as unknown as BoqRecord[]) || []).forEach((x) => { map[x.id] = x; });
        setBoqs(map);
      }
      if (rootIds.length) {
        // compute latest approved revision per family for staleness banner
        const { data: allBoqs } = await supabase
          .from("boqs").select("id, order_id, revision, verification_status");
        const { data: orders } = await supabase.from("orders").select("id, parent_order_id");
        const familyOf = new Map<string, string>();
        (orders || []).forEach((o) => familyOf.set(o.id as string, (o as { parent_order_id?: string | null; id: string }).parent_order_id || (o.id as string)));
        const latest: Record<string, number> = {};
        ((allBoqs as Array<{ order_id: string; revision: number; verification_status: string }>) || [])
          .filter((b) => b.verification_status === "approved")
          .forEach((b) => {
            const fam = familyOf.get(b.order_id) || b.order_id;
            if (latest[fam] == null || (b.revision ?? 0) > latest[fam]) latest[fam] = b.revision ?? 0;
          });
        setLatestRevByRoot(latest);
      }
      setLoading(false);
    })();
  }, []);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return reqs;
    return reqs.filter((r) => {
      const b = boqs[r.boq_id];
      return [r.requisition_number, b?.boq_number, b?.reference_oa_number, b?.client_name]
        .filter(Boolean).join(" ").toLowerCase().includes(q);
    });
  }, [reqs, boqs, search]);

  return (
    <div className="container mx-auto px-4 lg:px-6 py-5 space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">Requisitions</h1>
          <p className="text-xs text-muted-foreground">
            Material requisitions generated by Manufacturing from approved BOQs.
          </p>
        </div>
        <div className="relative">
          <Search className="absolute left-2 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input placeholder="Search requisition, OA, client…" className="h-8 pl-7 w-64"
                 value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
      </div>

      {loading ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : filtered.length === 0 ? (
        <Card>
          <CardContent className="py-10 text-center text-sm text-muted-foreground">
            No requisitions yet. Open an approved BOQ in Manufacturing and use "Create Requisition".
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-3">
          {filtered.map((r) => {
            const b = boqs[r.boq_id];
            const latest = latestRevByRoot[r.order_root_id];
            const stale = latest != null && latest > r.boq_revision;
            return (
              <Card key={r.id}>
                <CardContent className="py-4 flex flex-wrap items-center gap-4">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-sm">{r.requisition_number}</span>
                      <Badge variant="secondary">BOQ R{r.boq_revision}</Badge>
                      <Badge>{r.status}</Badge>
                      {stale && <Badge variant="destructive">BOQ revised to R{latest}</Badge>}
                    </div>
                    <div className="text-xs text-muted-foreground mt-1 truncate">
                      {b?.client_name || "—"} · OA {b?.reference_oa_number || "—"} · BOQ {b?.boq_number || "—"}
                    </div>
                  </div>
                  <div className="text-xs text-muted-foreground">Created: {fmtDate(r.created_at)}</div>
                  <Link to={`/requisitions/${r.id}`}><Button size="sm">Open</Button></Link>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}